// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using static Microsoft.Azure.PowerShell.Cmdlets.Compute.Runtime.Extensions;

namespace Microsoft.Azure.PowerShell.Cmdlets.Compute
{
    //Need to have an instance of ProxyClient in Module.cs, See "ClientAPI"
    public class ProxyClient
    {
        private VirtualMachinesOperations _virtualMachines;
        public VirtualMachinesOperations VirtualMachines => _virtualMachines;

        public ProxyClient (global::System.Management.Automation.PSCmdlet cmdlet, global::System.String subscriptionId = default(global::System.String))
        {
            if (subscriptionId != null) 
            {
                _subscriptionId = subscriptionId;
            }
            else
            {
                _subscriptionId = "default";
            }
            _virtualMachines = new VirtualMachinesOperations(this);

        }
        private string _subscriptionId;
        internal string SubscriptionId => _subscriptionId;
    }
}